### PR TITLE
Fix author template bug

### LINKED ISSUE #133: LHS: improve article view
https://main--24life--hlxsites.hlx.page/fitness/2021/jennifer-finds-the-power-to-persevere

- It briefly shows block data instead of hiding it
Screen Recording 2023-09-08 at 09 24 23

- Performance score is bad on mobile and desktop: https://pagespeed.web.dev/analysis/https-main--24life--hlxsites-hlx-page-fitness-2021-jennifer-finds-the-power-to-persevere/42gfoex9d4?form_factor=mobile
Screenshot 2023-09-08 at 09 26 19

### PR DESCRIPTION
**Pull request by rrusher**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #133

Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/fitness/2021/jennifer-finds-the-power-to-persevere
- After: https://author-bug--24life--hlxsites.hlx.live/fitness/2021/jennifer-finds-the-power-to-persevere

### CODE REVIEW

**Review by synox — APPROVED** [review]
looks good. Are you able to explain why it did not work properly before?

File: templates/article/article.js [hunk 1]
```diff
@@ -3,24 +3,25 @@ import {
 } from '../../scripts/lib-franklin.js';
 
 export default async function decorate(doc) {
+  // remove title and image from doc
+  doc.querySelector('main .section h1').remove();
+  doc.querySelector('main .section img').remove();
```
Comment (synox) [inline templates/article/article.js:8]: This breaks the video hero variant. I think this code needs to moved down into the `if (!videoHero) {`
