### PR TITLE
#31 Fixing mp4 autoplay on chrome firefox edge

### LINKED ISSUE #31: Magazine Article Hero Block with video
https://www.24life.com/the-change-master-john-berardis-second-act-will-help-you-too/

https://www.24life.com/graphic-designer-by-day-this-gx24-instructor-says-power-jumping-with-you-is-worth-it/

Note this is different from https://github.com/hlxsites/24life/issues/11

Screenshot 2023-07-31 at 11 54 13

### PR DESCRIPTION
**Pull request by iamitshri**
Additional testing revealed there was an issue autoplaying content without page interaction.  
Previously, only safari worked. Now Chrome, edge, firefox works too. 
The issue was about setting the boolean attribute.  

Fix #31 

Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/drafts/ashrigondeka/nutritionist-kelly-leveques-fab-four-to-get-in-shape

- After: 
- https://31-support-mp4-video-article-hero-block--24life--hlxsites.hlx.page/drafts/ashrigondeka/article-hero-video-1
- https://31-support-mp4-video-article-hero-block--24life--hlxsites.hlx.page/drafts/ashrigondeka/article-hero-video-2
- https://31-support-mp4-video-article-hero-block--24life--hlxsites.hlx.page/drafts/ashrigondeka/article-hero-video-3
- https://31-support-mp4-video-article-hero-block--24life--hlxsites.hlx.page/drafts/ashrigondeka/article-hero-video-4
- https://31-support-mp4-video-article-hero-block--24life--hlxsites.hlx.page/drafts/ashrigondeka/nutritionist-kelly-leveques-fab-four-to-get-in-shape

### CODE REVIEW

File: blocks/article-hero-video/article-hero-video.js [hunk 1]
```diff
@@ -101,10 +101,12 @@ function buildVideoTag(url) {
...
-  video.setAttribute('preload', 'auto');
-  video.setAttribute('autoplay', '');
-  video.setAttribute('muted', '');
-  video.setAttribute('loop', '');
+
+  // Set boolean attributes
+  video.muted = true;
+  video.autoplay = true;
+  video.loop = true;
+  video.setAttribute('muted', 'true');
```
Comment (synox) [inline blocks/article-hero-video/article-hero-video.js:109]: Muted set twice, and preloading not set. Is this the intention?

Comment (iamitshri) [reply blocks/article-hero-video/article-hero-video.js:109]: Preload did not have any effect. 

About muted: You can see with the current muted setting, the video in main branch **only** plays in safari, not in chrome, edge
https://main--24life--hlxsites.hlx.page/drafts/ashrigondeka/nutritionist-kelly-leveques-fab-four-to-get-in-shape

for firefox, this user-level setting should have played it, but it did not. It only plays when audio and video is allowed.  

image
